### ISSUE TITLE
Window dragging problems

### ISSUE THREAD

**Issue by MrCheatak** [ClementGre/ThreeFingersDragOnWindows#22] opened 2023-06-16 08:20 UTC
Window dragging works with most applications, but there seems to be a couple of exclusions. Some applications, despite being draggable with a click-hold, do not respond to three-finger-drag. The most peculiar case is the Task Manager as it is a system application. Other cases are Intel Extreme Tuning Utility, AOMEI Backup Professional, ThrottleStop and some installers. 
What could be the case?

**Comment by ClementGre** [comment] 2023-06-16 10:28
This might be related to #2, but this bug is fixed in the latest version of the app.
I'll try on my side to reproduce the issue.

**Comment by MrCheatak** [comment] 2023-06-16 13:42
Could indeed be an UWP problem. Task Manager is a part of Windows Tools collection, so I just tested dragging on apps from Windows Tools: Device manager (no), Defragment and Optimise Drives (yes), Services (no), Computer management (no), Registry Editor (no), System Information (yes) .... actually most of them are not responding to the drag.

**Comment by linitfor** [comment] 2023-07-14 01:35
The New Microsoft Edge Version.114, Microsoft Teams cannot be dragged too. Can you help to test ?

**Comment by MrCheatak** [comment] 2023-07-14 07:37
> The New Microsoft Edge Version.114, Microsoft Teams cannot be dragged too. Can you help to test ?

Both Microsoft Edge 114 and Teams can be dragged on my machine.
Windows 11 22H2.

**Comment by ClementGre** [comment] 2023-09-16 21:52
This issue is due to the TFDOW not runing as an elevated process (administrator). Then, the handler can't receive touchpads events when an elevated window is focused.

In the next release (v2.0), the handler will be an elevated process run at startup with a skipUAC technique, see #27.
Thank you.

**Closed by ClementGre** 2023-09-16 21:52 UTC
