### ISSUE TITLE
The dragging process is very clunky

### ISSUE THREAD

**Issue by lithiumleeow** [ClementGre/ThreeFingersDragOnWindows#14] opened 2022-12-01 14:33 UTC
First of all, thank you very much for your software, but when I used it after installation,
 I found that I was very stuck in the process of dragging with three fingers, and I could not use it normally at all. When I held down the touchpad with three fingers and moved the mouse, the window was very smooth. I don't know what the problem is, may I ask if it can be solved? I'm using Windows 11+ Apple Trackpad 2

The three-finger drag function of another software（fastgesture） is very smooth, but it has many functions I don't need, so I really hope this problem can be solved, thank you very much

**Comment by ClementGre** [comment] 2022-12-01 14:52
Hi @lithiumleeow,
do you have the same issue when performing a drag and drop on files and when selecting text ?

The three fingers drag does not work properly on the app main window because it is the application itself, then it is normal if the drag is laggy when moving the window of ThreeFingersDragOnWindows.

**Comment by lithiumleeow** [comment] 2022-12-02 03:13
> Hi @lithiumleeow, do you have the same issue when performing a drag and drop on files and when selecting text ?
> 
> The three fingers drag does not work properly on the app main window because it is the application itself, then it is normal if the drag is laggy when moving the window of ThreeFingersDragOnWindows.

files is same，i record it https://drive.google.com/file/d/1HmQ73exlcQljvgy9pQUIUPKLoAr6sOzh/view?usp=sharing

**Comment by ClementGre** [comment] 2022-12-02 07:29
Do you have the same issue with the version 1.0 ?
I added in the v1.1 a threshold that prevent detecting too much fingers on the touchpad :

https://github.com/ClementGre/ThreeFingersDragOnWindows/blob/f56c9a92a5a8e12cef51e6398ee2786ff829085d/src/touchpad/ContactsManager.cs#L49

Then, if your computer is sending less than one event every 20ms, it can not detect all of the fingers. Usually, events are sent every 3-8 ms, but it can be slower depending of your touchpad and your computer.

If you don't have issues with the v1.0, I'll try to change the threshold value to suit your computer.

**Comment by lithiumleeow** [comment] 2022-12-02 08:16
I tried version 1.0, very smooth! There is no stuck problem in version 1.1

**Comment by k-kruglov** [comment] 2022-12-08 22:40
I have the same issue with the last version, 1.0 was smooth for me, but had issues with UWP apps.

This fork works flawlessly https://github.com/gurinderhans/threefingerdrag/releases/tag/v0.0.1

**Comment by ClementGre** [comment] 2022-12-09 07:50
Ok, I changed the threshold from 20ms to 50ms.
Can you try this new version?
[ThreeFingersDragOnWindows.zip](https://github.com/ClementGre/ThreeFingersDragOnWindows/files/10192786/ThreeFingersDragOnWindows.zip)

You will also be able to see the events speed in the preferences window:
![Capture](https://user-images.githubusercontent.com/51322714/206651751-80544c4e-52ad-43c6-b024-594af7ac96fc.PNG)

Can you tell me what your event speed is? I had approximately 4-5 ms on all the laptops I tried.

**Comment by JeromeNelsonC** [comment] 2022-12-15 21:04
> Ok, I changed the threshold from 20ms to 50ms. Can you try this new version? [ThreeFingersDragOnWindows.zip](https://github.com/ClementGre/ThreeFingersDragOnWindows/files/10192786/ThreeFingersDragOnWindows.zip)
> 
> You will also be able to see the events speed in the preferences window: ![Capture](https://user-images.githubusercontent.com/51322714/206651751-80544c4e-52ad-43c6-b024-594af7ac96fc.PNG)
> 
> Can you tell me what your event speed is? I had approximately 4-5 ms on all the laptops I tried.

Mine is showing as 7ms

**Comment by JeromeNelsonC** [comment] 2022-12-15 21:07
I think the problem is that the program is trying to map the center of the 3 fingers (the mean position of the 3 fingers) thats why its clunky.
Can you make it map only the index finger (i.e the left most finger, for most people)

**Comment by ClementGre** [comment] 2022-12-15 21:18
It is not really average, it moves the cursor depending on the shift of the finger that moved more, just like on Mac OS.

I made a version that takes only into account the shift of the first finger placed on the touchpad:
[ThreeFingersDragOnWindows.zip](https://github.com/ClementGre/ThreeFingersDragOnWindows/files/10240707/ThreeFingersDragOnWindows.zip)

**Comment by JeromeNelsonC** [comment] 2022-12-15 23:03
Hmm.. but what did you change in version 1.1 that made it clunky? 
I noticed that can still tap with three fingers for a middle click (Thats how it is configured on my laptop anyway) in version 1.1 but not in version 1.0. Is that what could have caused the problem?
Btw the one which maps only one finger, moves in the opposite direction

**Comment by ClementGre** [comment] 2022-12-16 07:00
There were a lot of bugs fixed in the 1.1, and the algorithm changed quite a bit  adding ways to prevent issues like the fact that the three fingers are never placed or realeased exactly at the same time on the touchpad.
It is strange how taking the longest dist1nce makes it cluncky...
I'll try to reverse the direction and make a new version for you.

I think that the best thing to do would be for someone having this bug to try changing the source code and making a pull request.

**Comment by JeromeNelsonC** [comment] 2022-12-16 14:42
Well in your official 1.1 release, After fine tuning the acceleration and
velocity, it has turned out much smoother. But somehow version 1.0 feels
better.

**Comment by james-curtis** [comment] 2023-09-02 04:12
Yes, I also have some problems. At the end of three-finger dragging, the right button will be triggered inexplicably, and the movement speed is not satisfactory. I will try FastGestures. thank you also for your work

**Comment by james-curtis** [comment] 2023-09-02 04:19
> 

For redundant functions, a button can be used.

![image](https://github.com/ClementGre/ThreeFingersDragOnWindows/assets/49338067/b741c8c5-1895-466a-951d-5a59a71fef65)

**Comment by ClementGre** [comment] 2023-09-02 07:10
> Yes, I also have some problems. At the end of three-finger dragging, the right button will be triggered inexplicably, and the movement speed is not satisfactory. I will try FastGestures. thank you also for your work

Hi, the right click on release is related to #13. I'll look into it soon.

About the speed, doesn't the slider allows you to have the right speed ? Do you need a higher or lower speed ?

**Comment by ClementGre** [comment] 2023-09-11 09:53
Hi, I finally succeeded to reproduce your issue with an Apple magic trackpad 2 and this driver : https://github.com/imbushuo/mac-precision-touchpad

I am working right now on the version 2.0 of TFDW that will be a WinUI app and this issue should be fixed.
Thank's

**Comment by ClementGre** [comment] 2023-11-11 08:54
ThreeFingersDragOnWindows v2.0 has just been released. In this version, the dragging algorithm have been redeveloped from scratch, and it fixes this issue that I finally was able to reproduce.
[See release v2.0.1](https://github.com/ClementGre/ThreeFingersDragOnWindows/releases/tag/2.0.1)
Enjoy!

**Closed by ClementGre** 2023-11-11 08:54 UTC
Labels: bug
